[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[example]]
name = "day_1"
path = "day01/src/main.rs"

[[example]]
name = "day_2"
path = "day02/src/main.rs"
